config/routes.rb
Rails.application.routes.draw do

	
	#root route
	root 'books#index'
	#root 'book_collection#home_page'

	resources :books, path: '' do
		member do
			get :delete
		end
	end

	get 'book_collection/home_page'
	get 'book_collection/see_collection'
	get 'book_collection/enter_book'
	# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/book_collection_controller.rb
class BookCollectionController < ApplicationController
  def home_page
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def index
		@books = Book.order(:id)
	end

	def show
		@book = Book.find(params[:id])
	end

	def new
		@book = Book.new
	end

	def create
		#instantiate new object
		@book = Book.create(book_params)
		#save object
		if @book.save
			#save succedes
			redirect_to(books_path)
		else
			#save fails
			render('new')
		end
	end

	def edit	
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		if @book.update(book_params)
			#update succedes
			redirect_to(book_path(@book))
		else
			#update fails
			render('edit')
		end
	end

	def delete
		@book = Book.find(params[:id])
	end

	def destroy
		@book = Book.find(params[:id])
		@book.destroy
		redirect_to(books_path)
	end

	private

	def book_params
		params.require(:book).permit(:title, :author, :genre, :price, :published_date, :id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_collection_helper.rb
module BookCollectionHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/book_collection/enter_book.html.erb
<h1>Please enter a new book.</h1>
<%= link_to('View your book collection', "/book_collection/home_page") %> <br />

app/views/book_collection/home_page.html.erb
<h1>Welcome to your book collection!</h1>
<%= link_to('Enter a new book', "/book_collection/enter_book") %> <br />

app/views/books/delete.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books delete">
  <h2>Delete Book</h2>

  <%= form_for(@book, :method => 'delete') do |f| %>

  <p>Are you sure you want to permanently delete this book?</p>

  <p class="reference-name">
    <%= f.object.title %>
  </p>

  <div class="form-buttons">
    <%= f.submit("Delete Book") %>
  </div>

  <% end %>
</div>

app/views/books/edit.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books edit">
  <h2>Update Book</h2>

  <%= form_for(@book) do |f| %>

  <table summary="Subject form fields">
    <tr>
      <th>Title</th>
      <td>
        <%= f.text_field(:title) %>
      </td>
    </tr>
    <tr>
      <th>Author</th>
      <td>
        <%= f.text_field(:author) %>
      </td>
    </tr>
    <tr>
      <th>Genre</th>
      <td>
        <%= f.text_field(:genre) %>
      </td>
    </tr>
    <tr>
      <th>Price</th>
      <td>
        <%= f.number_field(:price) %>
      </td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td>
        <%= f.text_field(:published_date) %>
      </td>
    </tr>
  </table>

  <div class="form-buttons">
    <%= f.submit("Update Book") %>
  </div>

  <% end %>
</div>

app/views/books/index.html.erb
<div class="books index">
  <h2>Here are all your books!</h2>

  <%= link_to("Add New Book", new_book_path, :class => 'action new') %>

  <table class="listing" summary="Book list">
    <tr class="header">
      <th>Title</th>
      <th>Author</th>
      <th>Actions</th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td class="center">
        <%= book.title %>
      </td>
      <td class="center">
        <%= book.author %>
      <td class="actions">
        <%= link_to("Show", book_path(book), :class => 'action show') %>
        <%= link_to("Edit", edit_book_path(book), :class => 'action edit') %>
        <%= link_to("Delete", delete_book_path(book), :class => 'action delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/books/new.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="books new">
  <h2>Create Book</h2>

  <%= form_for(@book) do |f| %>

  <table summary="Book form fields">
    <tr>
      <th>Title</th>
      <td>
        <%= f.text_field(:title) %>
      </td>
    </tr>
    <tr>
      <th>Author</th>
      <td>
        <%= f.text_field(:author) %>
      </td>
    </tr>
    <tr>
      <th>Genre</th>
      <td>
        <%= f.select :genre, ['non fiction', 'fantacy', 'science fiction', 'horror', 'romance', 'other']%>
        </td>
    </tr>
    <tr>
      <th>Price</th>
      <td>
        <%= f.number_field(:price) %>
      </td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td>
        <%= f.date_select("published_date") %>
        </td>
    </tr>
  </table>

  <div class="form-buttons">
    <%= f.submit("Create Book") %>
  </div>

  <% end %>
</div>

app/views/books/show.html.erb
<%= link_to("<< Back to List", books_path, :class => 'back-link') %>

<div class="subjects show">
  <h2>Show Book</h2>

  <table summary="Subject detail view">
    <tr>
      <th>Title</th>
      <td>
        <%= @book.title %>
      </td>
    </tr>
    <tr>
      <th>Author</th>
      <td>
        <%= @book.author %>
      </td>
    </tr>
    <tr>
      <th>Genre</th>
      <td>
        <%= @book.genre %>
      </td>
    </tr>
    <tr>
      <th>Price</th>
      <td>
        <%= @book.price %>
      </td>
    </tr>
    <tr>
      <th>Published Date</th>
      <td>
        <%= @book.published_date %>
      </td>
    </tr>
  </table>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookCollection</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>